config/routes.rb
Rails.application.routes.draw do

  get 'notifications/pending_friendship' => 'notifications#pending_friendship'
  get 'friendships/accept_friend' => 'friendships#accept_friend'
  get 'comments/reply_on_post' => 'comments#reply_on_post'
  post 'friendships/invite' => 'friendships#invite'

  resources :activations
  resources :walls
  resources :posts
  resources :comments
  resources :allusers
  resources :friendships
  resources :notifications

  devise_for :users

  root 'questions#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  include AASM

  belongs_to :user
  belongs_to :friend, :class => 'User'

  aasm do
      state :pending_friendship , :initial => true
      state :friend
      state :block
      state :remove

      event :invitation do
         transitions :to => :pending_friendship
      end

      event :accepted do
          transitions :to => :friend
      end



  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :friendships
  has_many :friends, :through => :friendships



  include AASM
  before_create :create_activation_code
  after_create :account_conformation

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




         aasm do
           state :pending_activation, :initial => true
           state :activated
           state :removed


           event :activate do
             transitions :to => :activated
           end

           event :removed do
             transitions :to => :removed
           end
         end

     def account_conformation
       @user=User.last
        Conformation.welcome(@user).deliver_now
     end

    private

       def create_activation_code
           self.activation_code = SecureRandom.base64(15)
       end



end

app/controllers/allusers_controller.rb
class AllusersController < ApplicationController

  def index
     @all_users = User.where.not(:id=>current_user.id)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

  end

  def new
    @new_post = Post.new
    @email = params[:email]
  end

  def create
    @new_post = Post.create(post_params)
    if @new_post.save
      @new_post.user_id = params[:user_id]
       redirect_to walls_path
     end
  end

  def edit
     @edit_post = Post.find(params[:id])
  end


  private

    def post_params
       params.require(:post).permit(:text,:user_id)
    end

end

app/controllers/walls_controller.rb
class WallsController < ApplicationController

  def index


    @friend_from_logic = Friendship.where(:from_id=>current_user.id)
    @friend_to_logic = Friendship.where(:to_id=>current_user.id)

    @friend_from_logic.each do |friend_from|
      if friend_from.aasm_state == "friend"
        @from = friend_from.from_id
        @from_to = friend_from.to_id
      end
    end

    @friend_to_logic.each do |friend_to|
      if friend_to.aasm_state == "friend"
        @to = friend_to.to_id
        @to_from = friend_to.from_id
      end
    end

  if @friend_from_logic!=nil
     @from_posts = Post.where(:user_id=>@from)
     @to_posts = Post.where(:user_id=>@from_to)

  end


    if @friend_to_logic!=nil
       @from_posts_friends = Post.where(:user_id=>@to_from)
       @to_posts_friends = Post.where(:user_id=>@to)

    end

  end

end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/allusers_helper.rb
module AllusersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/allusers/index.html.erb
<h3>Listing all Users</h3>

<% @all_users.each do |user| %>
   <% if user.aasm_state == "activated" %>
      <%= user.email %>  <%= link_to "invite", friendships_path(:from_id=>current_user.id, :to_id=>user.id) %><br><br>        
   <% end %>

<% end %>

app/views/walls/index.html.erb
<h4><u>Posts</u></h4><br><br>


<div class="container">

  <%= link_to "new post", new_post_path(:email=>current_user.email) %><br><br>





            <% @from_posts.each do |post| %>
               <div class="row postbox">
                  User: <%= post.user.email %><br><br>
                  Post: <%= post.text %><br><br>
                  <%= link_to "comment", new_comment_path(:post_id=>post.id) %><br>
               </div><br><br>
            <% end %>


            <% @from_posts_friends.each do |post| %>
               <div class="row postbox">
                  User: <%= post.user.email %><br><br>
                  Post: <%= post.text %><br><br>
                  <%= link_to "comment", new_comment_path(:post_id=>post.id) %><br>
               </div><br><br>
            <% end %>




               <% @to_posts.each do |post| %>
                  <div class="row postbox">
                     User: <%= post.user.email %><br><br>
                     Post: <%= post.text %><br><br>
                     <%= link_to "comment", new_comment_path(:post_id=>post.id) %><br>
                  </div><br><br>
               <% end %>


               <% @to_posts_friends.each do |post| %>
                  <div class="row postbox">
                     User: <%= post.user.email %><br><br>
                     Post: <%= post.text %><br><br>
                     <%= link_to "comment", new_comment_path(:post_id=>post.id) %><br>
                  </div><br><br>
               <% end %>



</div>